name: fpi-e-register deployment

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Check out the repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # Step 2: Upload files to cPanel via FTP
      - name: Deploy via FTP
        uses: SamKirkland/FTP-Deploy-Action@4.2.0
        with:
          server: 192.64.84.226
          username: federalpolyilaro
          password: N3w5ever@ilar
          server-dir: /public_html/fpieregistry.federalpolyilaro.edu.ng/public
